sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t spotaddockers/react-test -f ./clientmy/Dockerfile.dev ./clientmy

script:
  - docker run -e CI=true spotaddockers/react-test npm test

after_success:
  - docker build -t spotaddockers/multi-clientmy ./clientmy
  - docker build -t spotaddockers/multi-nginx ./nginx
  - docker build -t spotaddockers/multi-server ./server
  - docker build -t spotaddockers/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push spotaddockers/multi-clientmy
  - docker push spotaddockers/multi-nginx
  - docker push spotaddockers/multi-server
  - docker push spotaddockers/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: 'us-west-1'
#  app: 'multi-docker'
#  env: 'Multidocker-env'
#  bucket_name: 'elasticbeanstalk-us-west-1-518447545674'
#  bucket_path: 'docker-multi'
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY